### ISSUE TITLE
GPS and DS18B20 sensor

### ISSUE THREAD

**Issue by sp2ong** [daveake/LoRaArduinoSerial#1]
Hi,

I would like use your solution to create TX Lora module to send XY coordinates and temperature on board modules  use DS18B20 and battery level in telemetry message. How to modify this code or you have ready example to LoRaArudinoTX with GPS modules and one sensor DS18B20 ???

I like your version because you have very nice tools to send parameters and we can test different modes to find optimal mode for transmission 

73 Waldek SP2ONG

**Comment by daveake** [comment]
See my flextrack code also on github.

Dave

**Comment by sp2ong** [comment]
Hi Dave,

Ah yes ! I see :-)  thanks.

But I have see in FlexTrack definition 

UAVANUT_LORA

not exist
#define WIREBUS 5  to use info form sensor DS18B20
and
 #define GPS_ON 2 to use GPS 


If I want to have information about temperature and GPS  in Lora message telemetry I need add this definition in  section UAVANUT_LORA ???
 
Waldek

**Comment by daveake** [comment]
You just need to create your own definition to match your hardware.  
e.g. copy the UAVANUT_LORA section, remove the GPS_ON bit (that's for 
trackers where the GPS has to be switched on via a MOSFET) and add the 
WIREBUS line to suit your circuit.

**Comment by sp2ong** [comment]
Ok thank you for information

Waldek SP2ONG

**Comment by sp2ong** [comment]
Only one question more Dave, do you have example of diagram for  UAVANUT-LORA ?

**Comment by daveake** [comment]
I don't, but perhaps ask Anthony Stirk as he did the design and PCB.  It's not been released but he may be happy to help :)
