### ISSUE TITLE
Some bugs of the actual version

### ISSUE THREAD

**Issue by Dieter9** [daveake/LoRaArduinoSerial#3]
Hi!

This software makes an uncomplicated impression and is the right thing to start with the LoRa reception of balloons. Unfortunately I found some problems with the current version.

1.) The README file of the project say's, that the serial baud rate is increased to 57,600 bd, as it is in the software LoRaSerialGateway.
But the code in line 187 is:     `Serial.begin(9600); // 57600);`
So the software don't wok together.
I changed the line 187 to:        `Serial.begin(57600); // 9600);`

2.) The README file and the header of the ino file told me to connect the Arduino port 8 to LoRa DIO0.
But the code in line 25 is:         `int dio0 = 3;`     That does not work.
I changed the line 25 to:           `int dio0 = 8;`     Now the Arduino works!

3.) It is not a bug, but it confused me. When I set the Frequency to `~F432.658` the Arduino answered with  `Frequency=432.65` . It takes me some time to see, that the frequency is processed right and that it is only a problem of the output. 

I changed line 335 from `Serial.println(Frequency); ` to  `Serial.println(Frequency,3);` . 
Now the output will give back 3 decimal places after the decimal point.

4.) When I received the first real signals from a balloon sonde, I noticed to get some messages twice times. It happened under poor receiving conditions. The reason for this seems to be the following:
In the subroutine **receiveMessage()** there is a crc-check. When it fails, the message string is leave unchanged and the subroutine returns the value 0 (Bytes). In the upper subroutine **CheckRx()** this case is not considered and the last message is processed again.

I added this command after line 605: 
`    if (Bytes > 0)`
`      // preventing printing the old message twice at crc errors`
`      {  `
and closed the bracket at the end of the subroutine. So no output is generated for packets with the length zero.

I hope my hints are useful and can be included in the release of a new version.

Best Regards
Dieter, DK6OV

**Comment by daveake** [comment]
Thanks Dieter I will look at these things this week.

Dave

**Comment by daveake** [comment]
Dieter,

> 1.) The README file of the project say's, that the serial baud rate is
increased to 57,600 bd, as it is in the software LoRaSerialGateway.

Oops.  That was supposed to be a local change (for different hardware) and
not make it back to github!

> 2.) The README file and the header of the ino file told me to connect the
Arduino port 8 to LoRa DIO0.

Same.

> 3.) It is not a bug, but it confused me. When I set the Frequency to
~F432.658 the Arduino answered with Frequency=432.65 . It takes me some
time to see, that the frequency is processed right and that it is only a
problem of the output.

Yes that annoyed me too.

> 4.) When I received the first real signals from a balloon sonde, I
noticed to get some messages twice times. It happened under poor receiving
conditions. The reason for this seems to be the following:

OK.  I did it slightly differently - same effect just different style:

    if (Bytes == 0)
    {
      // CRC fail do nothing
    }
    else if (Message[0] == '$') .....


New version going up soon.

Thanks!

Dave
